[package]
name = "sleepus-interruptus"
version = "0.1.0"
authors = ["Satoshi Nakamura <snak@snak.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = { version = "1.6.3", features = ["attributes"] }
